#!/usr/bin/env python3
"""Build the Migration Matrix snapshot (contract 1.0) and push it to the app.

  push_snapshot.py                 build + validate + print a summary
  push_snapshot.py --fixture       write ../contract/fixture-v1.json (the
                                   committed fixture is ALWAYS generated by
                                   this flag, never hand-written)
  push_snapshot.py --dry-run [URL] POST with dry_run:true (server validates,
                                   touches nothing)
  push_snapshot.py --post [URL]    real POST (stores a snapshot)
  push_snapshot.py --heartbeat [URL]  POST a heartbeat only

Token: MM_INGEST_TOKEN env var, else ~/.mm-ingest-token (one line, 600).
Default URL: http://localhost:3001/api/migration/ingest
Optional ../contract/sources-weburls.json maps file basenames to SharePoint
web URLs so the dashboard's spreadsheet buttons open Excel Online.

Run AFTER run_all.py (it reads the freshly built present.html + master state).
Respects MM_SOURCE / MM_MATRIX_DIR like the rest of the pipeline.
"""
import datetime
import hashlib
import json
import os
import re
import sys
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_master as bm  # noqa: E402
import chat_server  # noqa: E402
import client_matrix as cm  # noqa: E402

DEFAULT_URL = "http://localhost:3001/api/migration/ingest"
FIXTURE = os.path.join(HERE, "contract", "fixture-v1.json")
URLMAP = os.path.join(HERE, "contract", "sources-weburls.json")


def sha256(path):
    h = hashlib.sha256()
    h.update(open(path, "rb").read())
    return h.hexdigest()


def get_token():
    t = os.environ.get("MM_INGEST_TOKEN", "").strip()
    if t:
        return t
    p = os.path.expanduser("~/.mm-ingest-token")
    if os.path.exists(p):
        return open(p).read().strip()
    return None


def utc(ts=None):
    dt = (datetime.datetime.utcfromtimestamp(ts) if ts
          else datetime.datetime.utcnow())
    return dt.replace(microsecond=0).isoformat() + "Z"


def build_snapshot():
    html = open(os.path.join(HERE, "present.html")).read()
    data = json.loads(re.search(r"const DATA = (\{.*?\});\n", html, re.S).group(1))
    facts = json.loads(chat_server.facts_blob())

    # findings persisted by build_master.main() at build time; rebuilding
    # here would clobber master.db before client-matrix ingest (a bug the
    # first e2e run caught): read the file instead
    fpath = os.path.join(HERE, "findings.json")
    raw = json.load(open(fpath)) if os.path.exists(fpath) else []
    findings = [{"severity": f["severity"], "code": f["check"],
                 "message": f["detail"], "location": ""} for f in raw]

    urlmap = {}
    if os.path.exists(URLMAP):
        try:
            urlmap = json.load(open(URLMAP))
        except Exception:
            pass

    def fmeta(path):
        base = os.path.basename(path)
        return {"name": base, "sha256": sha256(path),
                "mtime": utc(os.path.getmtime(path)),
                "web_url": urlmap.get(base, "")}

    return {
        "contract": "1.0",
        "generated_at": utc(),
        "source": os.environ.get("MM_SOURCE_NAME", "mac-agent"),
        "source_files": {
            "tracker": fmeta(os.path.abspath(bm.SRC)),
            "matrices": [fmeta(p) for p in cm.find_matrices()],
            "folder_url": urlmap.get("_folder", ""),
        },
        "week": str(bm.CUR_WEEK),
        "week_lbl": str(data.get("week_lbl", "")),
        "data": data,
        "facts": facts,
        "findings": findings,
    }


def problems(s):
    """Local mirror of the server's snapshotProblems guards."""
    p = []
    if not re.match(r"^1\.\d+$", s.get("contract", "")):
        p.append("contract must be a '1.x' string")
    if not isinstance(s.get("generated_at"), str):
        p.append("generated_at missing")
    sf = s.get("source_files") or {}
    if not isinstance((sf.get("tracker") or {}).get("sha256"), str):
        p.append("source_files.tracker.sha256 missing")
    if not isinstance(sf.get("matrices"), list):
        p.append("source_files.matrices must be an array")
    d = s.get("data") or {}
    if not (isinstance(d.get("clients"), list) and isinstance(d.get("team"), list)
            and isinstance(d.get("overview"), dict)):
        p.append("data must carry clients[], team[], overview")
    if not isinstance(s.get("facts"), dict):
        p.append("facts missing")
    if not isinstance(s.get("findings"), list):
        p.append("findings must be an array")
    return p


def post(url, payload, token):
    body = json.dumps(payload).encode()
    req = urllib.request.Request(url, data=body, headers={
        "Content-Type": "application/json", "x-mm-ingest-token": token})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return resp.status, json.load(resp)
    except urllib.error.HTTPError as e:
        try:
            return e.code, json.load(e)
        except Exception:
            return e.code, {"error": e.read().decode()[:300]}


def main():
    args = sys.argv[1:]
    url = next((a for a in args if a.startswith("http")), DEFAULT_URL)

    if "--heartbeat" in args:
        token = get_token()
        if not token:
            sys.exit("no token: set MM_INGEST_TOKEN or ~/.mm-ingest-token")
        code, out = post(url, {"heartbeat": True, "detail": "agent alive"}, token)
        print(code, json.dumps(out))
        sys.exit(0 if code == 200 else 1)

    snap = build_snapshot()
    probs = problems(snap)
    if probs:
        sys.exit("snapshot fails local validation: " + "; ".join(probs))
    size = len(json.dumps(snap))
    print(f"snapshot OK: contract {snap['contract']}, week {snap['week_lbl']}, "
          f"{len(snap['data']['clients'])} clients, "
          f"{len(snap['findings'])} findings, {size/1024:.1f} KB")

    if "--fixture" in args:
        os.makedirs(os.path.dirname(FIXTURE), exist_ok=True)
        json.dump(snap, open(FIXTURE, "w"), indent=1)
        print(f"fixture written: {os.path.relpath(FIXTURE, HERE)}")
        return
    if "--dry-run" in args or "--post" in args:
        token = get_token()
        if not token:
            sys.exit("no token: set MM_INGEST_TOKEN or ~/.mm-ingest-token")
        if "--dry-run" in args:
            snap["dry_run"] = True
        code, out = post(url, snap, token)
        print(code, json.dumps(out)[:400])
        sys.exit(0 if code in (200, 201) else 1)


if __name__ == "__main__":
    main()
