#!/usr/bin/env node
/**
 * One-shot extractor: reads the canonical Stamats gap-analysis HTML template
 * (coe-gap-analysis-report.html) and writes the static-CSS and static-JS
 * chunks out as ES-module files under templates/.
 *
 * Run once: `node packages/server/src/reports/extractor.mjs`
 * Re-run whenever the canonical HTML template changes visually.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, "..", "..", "..", "..")
const SRC = resolve(REPO_ROOT, "coe-gap-analysis-report.html")
const OUT_DIR = resolve(__dirname, "templates")

const html = readFileSync(SRC, "utf8")

/** Extract inner content of the Nth occurrence (0-indexed) of a tag. */
function extractTagContent(source, tag, index) {
  const openRe = new RegExp(`<${tag}(?:[^>]*)>`, "g")
  const closeRe = new RegExp(`</${tag}>`, "g")
  const opens = []
  const closes = []
  let m
  while ((m = openRe.exec(source)) !== null) opens.push(m.index + m[0].length)
  while ((m = closeRe.exec(source)) !== null) closes.push(m.index)
  if (index >= opens.length || index >= closes.length) {
    throw new Error(`<${tag}> index ${index} not found (have ${opens.length})`)
  }
  return source.slice(opens[index], closes[index])
}

// Three <style> blocks: main, ai-intro, chat
const mainStyles = extractTagContent(html, "style", 0)
const introStyles = extractTagContent(html, "style", 1)
const chatStyles = extractTagContent(html, "style", 2)

// Pick the runtime <script> block (skip the `type="application/ld+json"` one in <head>).
function extractRuntimeScript(source) {
  const openRe = /<script(?![^>]*type=)[^>]*>/gi
  const open = openRe.exec(source)
  if (!open) throw new Error("Runtime <script> not found")
  const start = open.index + open[0].length
  const close = source.indexOf("</script>", start)
  if (close === -1) throw new Error("Runtime </script> not found")
  return source.slice(start, close)
}
const scriptBody = extractRuntimeScript(html)

// The reportData object is injected per-call; strip the hardcoded coe block and the botReply
// function from the script template. We'll replace them with placeholders.
// Find start and end markers in the script body.
const reportDataStart = scriptBody.indexOf("const reportData=")
if (reportDataStart === -1) throw new Error("reportData declaration not found")
// Find the `function botReply(` that follows
const botReplyStart = scriptBody.indexOf("function botReply", reportDataStart)
if (botReplyStart === -1) throw new Error("botReply function not found")
// Find end of botReply — track braces from `function botReply(q){`
const botReplyOpenBrace = scriptBody.indexOf("{", botReplyStart)
let depth = 0
let botReplyEnd = -1
for (let i = botReplyOpenBrace; i < scriptBody.length; i++) {
  if (scriptBody[i] === "{") depth++
  else if (scriptBody[i] === "}") {
    depth--
    if (depth === 0) {
      botReplyEnd = i + 1
      break
    }
  }
}
if (botReplyEnd === -1) throw new Error("botReply end brace not found")

const scriptPrefix = scriptBody.slice(0, reportDataStart).trimEnd()
const scriptSuffix = scriptBody.slice(botReplyEnd).trimStart()

/** Wrap a string as a TS module exporting a backtick template literal. Escapes ${ and backticks. */
function asTsString(value, exportName) {
  const escaped = value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")
  return `// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.\n// Re-run \`node packages/server/src/reports/extractor.mjs\` after editing coe-gap-analysis-report.html.\nexport const ${exportName} = \`${escaped}\`\n`
}

writeFileSync(resolve(OUT_DIR, "styles.main.ts"), asTsString(mainStyles, "MAIN_STYLES"))
writeFileSync(resolve(OUT_DIR, "styles.intro.ts"), asTsString(introStyles, "INTRO_STYLES"))
writeFileSync(resolve(OUT_DIR, "styles.chat.ts"), asTsString(chatStyles, "CHAT_STYLES"))

writeFileSync(
  resolve(OUT_DIR, "scripts.static.ts"),
  `// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.\n` +
    `// Two halves of the runtime script: before and after the per-report data + botReply injection.\n` +
    asTsString(scriptPrefix, "SCRIPT_PREFIX").replace("export const", "export const ") +
    `\n` +
    asTsString(scriptSuffix, "SCRIPT_SUFFIX").replace("export const", "export const "),
)

console.log("Extracted:")
console.log(`  main styles   ${mainStyles.length} chars`)
console.log(`  intro styles  ${introStyles.length} chars`)
console.log(`  chat styles   ${chatStyles.length} chars`)
console.log(`  script prefix ${scriptPrefix.length} chars`)
console.log(`  script suffix ${scriptSuffix.length} chars`)
