// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.
// Two halves of the runtime script: before and after the per-report data + botReply injection.
// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.
// Re-run `node packages/server/src/reports/extractor.mjs` after editing coe-gap-analysis-report.html.
export const  SCRIPT_PREFIX = `
// Reveal observer
const io=new IntersectionObserver(e=>{e.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');io.unobserve(x.target)}})},{threshold:.05,rootMargin:'0px 0px -20px 0px'});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));

// Gauge observer
const gio=new IntersectionObserver(e=>{e.forEach(x=>{if(x.isIntersecting){x.target.classList.add('gauge-visible');gio.unobserve(x.target)}})},{threshold:.25});
document.querySelectorAll('.cat-score-card').forEach(el=>gio.observe(el));

// ── Single scroll handler via rAF (no jank) ─────────
const sp=document.getElementById('scrollProgress');
const sn=document.getElementById('stickyNav');
let ticking=false;
let cachedWidth=window.innerWidth;
window.addEventListener('resize',()=>{cachedWidth=window.innerWidth},{passive:true});

function onScroll(){
  const sy=window.scrollY;
  const docH=document.documentElement.scrollHeight-window.innerHeight;
  // Progress bar
  sp.style.width=(sy/docH*100)+'%';
  // Nav visibility
  const show=sy>window.innerHeight*.55;
  sn.classList.toggle('show',show);
  if(cachedWidth>1080){document.body.classList.toggle('nav-open',show)}
  else{document.body.classList.remove('nav-open')}
  ticking=false;
}
window.addEventListener('scroll',()=>{
  if(!ticking){requestAnimationFrame(onScroll);ticking=true}
},{passive:true});

// Count up
const cio=new IntersectionObserver(e=>{e.forEach(x=>{if(!x.isIntersecting)return;const el=x.target,t=+el.dataset.target;let c=0;const s=Math.max(1,Math.ceil(t/50));const id=setInterval(()=>{c=Math.min(c+s,t);el.textContent=c;if(c>=t)clearInterval(id)},20);cio.unobserve(el)})},{threshold:.5});
document.querySelectorAll('.count-up').forEach(el=>cio.observe(el));

// Schema tabs
document.querySelectorAll('.tab-btn').forEach(btn=>{
  btn.addEventListener('click',()=>{
    document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));
    document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));
    btn.classList.add('active');
    document.getElementById('tab-'+btn.dataset.tab).classList.add('active');
  });
});

// Smooth scroll nav
document.querySelectorAll('.sticky-nav a').forEach(a=>{a.addEventListener('click',e=>{e.preventDefault();document.querySelector(a.getAttribute('href'))?.scrollIntoView({behavior:'smooth',block:'start'})})});

// ── AI Intro Popup ───────────────────────────────────
const aiIntro=document.getElementById('aiIntro');
const aiIntroCta=document.getElementById('aiIntroCta');
const aiIntroDismiss=document.getElementById('aiIntroDismiss');
// Show after 3 seconds — only once per visitor
if(!localStorage.getItem('coe-report-intro-seen')){
  setTimeout(()=>{aiIntro.classList.add('show')},8000);
}

function closeIntro(openChat){
  aiIntro.classList.remove('show');
  localStorage.setItem('coe-report-intro-seen','1');
  if(openChat){
    setTimeout(()=>{chatPanel.classList.add('open');chatFab.classList.add('hidden');chatInput.focus()},400);
  }
}
aiIntroCta.addEventListener('click',()=>closeIntro(true));
aiIntroDismiss.addEventListener('click',()=>closeIntro(false));
// Chip clicks open chat with that question
document.querySelectorAll('.ai-intro-chip').forEach(c=>{
  c.addEventListener('click',()=>{
    closeIntro(true);
    const q=c.dataset.q;
    setTimeout(()=>{
      chatInput.value=q;
      chatForm.dispatchEvent(new Event('submit'));
    },600);
  });
});

// ── Escape/overlay dismiss for AI intro ──
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&aiIntro.classList.contains('show'))closeIntro(false)});
aiIntro.addEventListener('click',e=>{if(e.target===aiIntro)closeIntro(false)});

// ── Active nav section tracking ──
const navLinks=document.querySelectorAll('.sticky-nav a[href^="#"]');
const trackedSections=[];
navLinks.forEach(a=>{const id=a.getAttribute('href')?.replace('#','');if(id){const s=document.getElementById(id);if(s)trackedSections.push({el:s,link:a})}});
const nio=new IntersectionObserver(e=>{e.forEach(x=>{if(x.isIntersecting){navLinks.forEach(a=>a.classList.remove('active'));const m=trackedSections.find(s=>s.el===x.target);if(m)m.link.classList.add('active')}})},{threshold:0,rootMargin:'-20% 0px -70% 0px'});
trackedSections.forEach(s=>nio.observe(s.el));

// ── Chatbot ──────────────────────────────────────────
const chatFab=document.getElementById('chatFab');
const chatPanel=document.getElementById('chatPanel');
const chatClose=document.getElementById('chatClose');
const chatForm=document.getElementById('chatForm');
const chatInput=document.getElementById('chatInput');
const chatMessages=document.getElementById('chatMessages');

chatFab.addEventListener('click',()=>{chatPanel.classList.add('open');chatFab.classList.add('hidden');chatInput.focus()});
chatClose.addEventListener('click',()=>{chatPanel.classList.remove('open');chatFab.classList.remove('hidden')});`

// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.
// Re-run `node packages/server/src/reports/extractor.mjs` after editing coe-gap-analysis-report.html.
export const  SCRIPT_SUFFIX = `chatForm.addEventListener('submit',e=>{
  e.preventDefault();
  const q=chatInput.value.trim();
  if(!q)return;
  // User message
  const um=document.createElement('div');
  um.className='chat-msg user';um.textContent=q;
  chatMessages.appendChild(um);
  chatInput.value='';
  chatMessages.scrollTop=chatMessages.scrollHeight;
  // Typing indicator
  const ti=document.createElement('div');
  ti.className='chat-msg bot typing';ti.textContent='Thinking...';
  chatMessages.appendChild(ti);
  chatMessages.scrollTop=chatMessages.scrollHeight;
  // Bot reply after brief delay
  setTimeout(()=>{
    ti.remove();
    const bm=document.createElement('div');
    bm.className='chat-msg bot';
    bm.innerHTML=botReply(q).replace(/\\*\\*(.*?)\\*\\*/g,'<strong>$1</strong>');
    chatMessages.appendChild(bm);
    chatMessages.scrollTop=chatMessages.scrollHeight;
  },600+Math.random()*400);
});
`
