// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.
// Re-run `node packages/server/src/reports/extractor.mjs` after editing coe-gap-analysis-report.html.
export const MAIN_STYLES = `
/* ═══════════════════════════════════════════════════════════════
   FOUNDATION
   ═══════════════════════════════════════════════════════════════ */
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}

:root{
  --bg:#050810;
  --bg-surface:#0a0e1a;
  --bg-card:rgba(14,19,36,.65);
  --bg-card-solid:#0e1324;
  --bg-card-hover:rgba(22,29,53,.8);
  --bg-glass:rgba(14,19,36,.45);
  --border:rgba(255,255,255,.07);
  --border-hover:rgba(255,255,255,.12);
  --border-glow:rgba(129,140,248,.15);
  --text:#f1f5f9;
  --text-secondary:#94a3b8;
  --text-muted:#64748b;
  --accent:#818cf8;
  --accent-bright:#a5b4fc;
  --accent-dim:rgba(129,140,248,.12);
  --critical:#f87171;
  --critical-bg:rgba(248,113,113,.06);
  --critical-border:rgba(248,113,113,.12);
  --high:#fbbf24;
  --high-bg:rgba(251,191,36,.06);
  --high-border:rgba(251,191,36,.12);
  --medium:#60a5fa;
  --medium-bg:rgba(96,165,250,.06);
  --medium-border:rgba(96,165,250,.12);
  --low:#34d399;
  --low-bg:rgba(52,211,153,.06);
  --low-border:rgba(52,211,153,.12);
  --purple:#a78bfa;--purple-bg:rgba(167,139,250,.06);--purple-border:rgba(167,139,250,.12);
  --grad-hero:linear-gradient(135deg,#818cf8 0%,#c084fc 40%,#f472b6 100%);
  --grad-critical:linear-gradient(135deg,#dc2626,#f87171);
  --grad-high:linear-gradient(135deg,#d97706,#fbbf24);
  --grad-medium:linear-gradient(135deg,#2563eb,#60a5fa);
  --grad-low:linear-gradient(135deg,#059669,#34d399);
  --r-xl:24px;--r-lg:16px;--r-md:12px;--r-sm:8px;
  --ease:cubic-bezier(.16,1,.3,1);
  --shadow-sm:0 2px 8px rgba(0,0,0,.2);
  --shadow-md:0 8px 32px rgba(0,0,0,.3);
  --shadow-lg:0 24px 64px -16px rgba(0,0,0,.5);
  --shadow-xl:0 40px 100px -20px rgba(0,0,0,.6);
  --shadow-glow:0 0 80px -20px rgba(129,140,248,.15);
}

html{scroll-behavior:smooth;scroll-padding-top:100px}
@media(min-width:1081px){html{scroll-padding-top:60px}}
body{
  font-family:-apple-system,'system-ui','SF Pro Display','SF Pro Text',Inter,'Segoe UI',sans-serif;
  background:var(--bg);color:var(--text);
  line-height:1.65;-webkit-font-smoothing:antialiased;
  overflow-x:hidden;
}
::selection{background:rgba(129,140,248,.3);color:#fff}
*:focus-visible{outline:2px solid var(--accent);outline-offset:3px;border-radius:var(--r-sm)}
a{color:var(--accent);text-decoration:none;transition:color .2s}
a:hover{color:var(--accent-bright)}

/* ═══════════════════════════════════════════════════════════════
   AMBIENT CANVAS
   ═══════════════════════════════════════════════════════════════ */
/* Ambient glow — uses radial-gradient instead of filter:blur for zero GPU cost */
.ambient{position:fixed;inset:0;z-index:-1;pointer-events:none;
  background:
    radial-gradient(ellipse 50% 45% at 85% 10%, rgba(99,102,241,.06) 0%, transparent 70%),
    radial-gradient(ellipse 45% 50% at 10% 70%, rgba(168,85,247,.04) 0%, transparent 70%),
    radial-gradient(ellipse 40% 40% at 60% 45%, rgba(244,114,182,.025) 0%, transparent 70%);
}

/* Grain — removed for performance (full-viewport SVG filter was causing compositing on every frame) */

/* Mesh gradient for hero background */
.hero-mesh{
  position:absolute;inset:0;overflow:hidden;pointer-events:none;z-index:0;
}
.hero-mesh::before{
  content:'';position:absolute;width:140%;height:140%;top:-20%;left:-20%;
  background:
    radial-gradient(ellipse 60% 50% at 20% 50%, rgba(99,102,241,.12) 0%, transparent 70%),
    radial-gradient(ellipse 50% 60% at 80% 30%, rgba(168,85,247,.09) 0%, transparent 70%),
    radial-gradient(ellipse 40% 50% at 60% 80%, rgba(244,114,182,.06) 0%, transparent 70%);
}

/* ═══════════════════════════════════════════════════════════════
   SCROLL PROGRESS
   ═══════════════════════════════════════════════════════════════ */
.scroll-progress{
  position:fixed;top:0;left:0;height:2px;z-index:1001;
  background:var(--grad-hero);width:0%;
  box-shadow:0 0 24px rgba(129,140,248,.5),0 0 6px rgba(129,140,248,.3);
}

/* ═══════════════════════════════════════════════════════════════
   STICKY NAV
   ═══════════════════════════════════════════════════════════════ */
.sticky-nav{
  position:fixed;top:0;left:0;right:0;z-index:1000;
  background:rgba(5,8,16,.85);
  backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);
  border-bottom:1px solid var(--border);
  transform:translateY(-100%);transition:transform .45s var(--ease);
  will-change:transform;
}
.sticky-nav.show{transform:translateY(0)}
.sticky-nav-inner{
  max-width:1320px;margin:0 auto;padding:0 28px;
  display:flex;align-items:center;height:52px;gap:4px;
  overflow-x:auto;scrollbar-width:none;
}
.sticky-nav-inner::-webkit-scrollbar{display:none}
/* Desktop: sidebar nav */
@media(min-width:1081px){
  .sticky-nav{
    top:44px;left:0;right:auto;bottom:0;width:200px;
    border-bottom:none;border-right:1px solid var(--border);
    transform:translateX(-100%);
  }
  .sticky-nav.show{transform:translateX(0)}
  .sticky-nav-inner{
    flex-direction:column;align-items:stretch;height:auto;
    padding:20px 14px;gap:3px;overflow-y:auto;overflow-x:hidden;
    max-height:calc(100vh - 44px);
  }
  .nav-brand{
    font-weight:700;font-size:.78rem;color:var(--text);
    margin:0 0 14px;padding:0 0 14px;
    border-right:none;border-bottom:1px solid var(--border);
    white-space:nowrap;
    background:var(--grad-hero);-webkit-background-clip:text;
    -webkit-text-fill-color:transparent;background-clip:text;
  }
  .sticky-nav a{
    color:var(--text-muted);font-size:.74rem;font-weight:500;
    white-space:nowrap;padding:7px 10px;border-radius:6px;
    transition:all .2s;letter-spacing:.01em;display:block;position:relative;
  }
  .sticky-nav a:hover{color:var(--text);background:rgba(255,255,255,.06)}
  .sticky-nav a.active{color:var(--accent-bright);background:rgba(129,140,248,.08)}
  .sticky-nav a.active::before{content:'';position:absolute;left:0;top:6px;bottom:6px;width:2px;background:var(--grad-hero);border-radius:2px}
  body.nav-open{margin-left:200px}
}
/* Mobile/tablet: top bar nav */
@media(max-width:1080px){
  .nav-brand{
    font-weight:700;font-size:.78rem;color:var(--text);
    margin-right:16px;padding-right:20px;
    border-right:1px solid var(--border);
    white-space:nowrap;flex-shrink:0;
    background:var(--grad-hero);-webkit-background-clip:text;
    -webkit-text-fill-color:transparent;background-clip:text;
  }
  .sticky-nav a{
    color:var(--text-muted);font-size:.72rem;font-weight:500;
    white-space:nowrap;padding:6px 12px;border-radius:6px;
    transition:all .2s;letter-spacing:.01em;
  }
  .sticky-nav a:hover{color:var(--text);background:rgba(255,255,255,.06)}
}

/* ═══════════════════════════════════════════════════════════════
   LAYOUT
   ═══════════════════════════════════════════════════════════════ */
.container{max-width:1320px;margin:0 auto;padding:0 28px}
@media(max-width:640px){.container{padding:0 20px}}
@media(max-width:500px){.container{padding:0 16px}}
section{padding:100px 0}
@media(max-width:768px){section{padding:64px 0}}
@media(max-width:500px){section{padding:48px 0}}

/* ═══════════════════════════════════════════════════════════════
   REVEAL SYSTEM
   ═══════════════════════════════════════════════════════════════ */
.reveal{
  opacity:0;transform:translateY(28px);
  transition:opacity .9s var(--ease),transform .9s var(--ease);
}
.reveal.visible{opacity:1;transform:translateY(0)}

/* Staggered children */
.stagger > .reveal:nth-child(1){transition-delay:.05s}
.stagger > .reveal:nth-child(2){transition-delay:.1s}
.stagger > .reveal:nth-child(3){transition-delay:.15s}
.stagger > .reveal:nth-child(4){transition-delay:.2s}
.stagger > .reveal:nth-child(5){transition-delay:.25s}
.stagger > .reveal:nth-child(6){transition-delay:.3s}
.stagger > .reveal:nth-child(7){transition-delay:.35s}
.stagger > .reveal:nth-child(8){transition-delay:.4s}
.stagger > .reveal:nth-child(9){transition-delay:.45s}
.stagger > .reveal:nth-child(10){transition-delay:.5s}

/* ═══════════════════════════════════════════════════════════════
   TYPOGRAPHY
   ═══════════════════════════════════════════════════════════════ */
h1,h2,h3,h4{font-weight:600;letter-spacing:-.025em;line-height:1.2}
h1{font-size:clamp(2rem,5.5vw,4rem);font-weight:700}
h2{font-size:clamp(1.5rem,3.2vw,2.2rem);font-weight:600}
h3{font-size:1.1rem;font-weight:600}

.section-label{
  display:inline-flex;align-items:center;gap:10px;
  font-size:.68rem;font-weight:600;text-transform:uppercase;letter-spacing:.2em;
  color:var(--accent);margin-bottom:20px;
}
.section-label::before{
  content:'';width:32px;height:2px;
  background:var(--grad-hero);border-radius:2px;
}
.subtitle{
  font-size:clamp(1rem,1.8vw,1.12rem);
  color:var(--text-secondary);max-width:720px;line-height:1.8;
  font-weight:400;
}

/* ═══════════════════════════════════════════════════════════════
   GLASS CARD MIXIN
   ═══════════════════════════════════════════════════════════════ */
.glass{
  background:var(--bg-card);
    border:1px solid var(--border);
  border-radius:var(--r-lg);
  transition:all .4s var(--ease);
}
.glass:hover{
  background:var(--bg-card-hover);
  border-color:var(--border-hover);
  transform:translateY(-4px);
  box-shadow:var(--shadow-md);
}

/* Glow hover — removed mask-composite, using simple border-color transition instead */

/* ═══════════════════════════════════════════════════════════════
   HERO
   ═══════════════════════════════════════════════════════════════ */
.hero{
  min-height:100vh;min-height:100dvh;
  display:flex;align-items:center;
  padding:140px 0 80px;position:relative;
}
.hero-grid{
  display:grid;grid-template-columns:1.15fr 1fr;
  gap:72px;align-items:center;position:relative;z-index:1;
}
.hero-badge{
  display:inline-flex;align-items:center;gap:10px;
  padding:8px 22px 8px 14px;
  background:rgba(248,113,113,.05);
  border:1px solid rgba(248,113,113,.15);
  border-radius:100px;
  font-size:.76rem;font-weight:600;color:var(--critical);
  margin-bottom:32px;
  box-shadow:0 0 30px -10px rgba(248,113,113,.15);
}
.pulse-dot{
  width:8px;height:8px;border-radius:50%;
  background:var(--critical);position:relative;
  box-shadow:0 0 8px var(--critical);
}
.pulse-dot::after{
  content:'';position:absolute;inset:-5px;border-radius:50%;
  border:2px solid var(--critical);
  animation:ping 1.8s cubic-bezier(0,0,.2,1) infinite;
}
@keyframes ping{0%{transform:scale(1);opacity:.5}100%{transform:scale(2.4);opacity:0}}

.hero h1{margin-bottom:28px}
.gradient-text{
  background:var(--grad-hero);
  -webkit-background-clip:text;-webkit-text-fill-color:transparent;
  background-clip:text;color:transparent;
  background-size:200% 200%;
  animation:gradient-shift 6s ease-in-out infinite;
  filter:drop-shadow(0 0 30px rgba(129,140,248,.15));
}
@keyframes gradient-shift{
  0%,100%{background-position:0% 50%}
  50%{background-position:100% 50%}
}

.hero-visual{position:relative;perspective:1200px}
.hero-screenshot{
  width:100%;border-radius:var(--r-xl);
  border:1px solid rgba(255,255,255,.08);
  box-shadow:var(--shadow-xl),0 0 0 1px rgba(255,255,255,.03),0 0 80px -20px rgba(99,102,241,.1);
  transition:transform .6s var(--ease);
}
.hero-visual:hover .hero-screenshot{transform:rotateY(-3deg) rotateX(2deg) scale(1.02)}

/* Floating tags */
.float-tag{
  position:absolute;padding:10px 18px;
  background:rgba(10,14,26,.85);
    border:1px solid var(--border);border-radius:var(--r-md);
  font-size:.75rem;font-weight:600;
  box-shadow:var(--shadow-lg);
  animation:tag-bob 5s ease-in-out infinite;z-index:2;
  letter-spacing:.01em;
}
.float-tag.ft1{top:8%;right:-32px;color:var(--critical);animation-delay:0s}
.float-tag.ft2{bottom:32%;left:-40px;color:var(--high);animation-delay:1.5s}
.float-tag.ft3{bottom:6%;right:-24px;color:var(--medium);animation-delay:3s}
@keyframes tag-bob{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}

/* Decorative rings */
.deco-ring{
  position:absolute;border:1.5px solid rgba(129,140,248,.08);
  border-radius:50%;pointer-events:none;
}
.deco-ring:nth-child(1){width:420px;height:420px;top:-80px;right:-120px}
.deco-ring:nth-child(2){width:260px;height:260px;bottom:-40px;left:-60px;opacity:.6}
.deco-ring:nth-child(3){width:160px;height:160px;top:30%;right:20%;border-color:rgba(244,114,182,.04);opacity:.5}

@media(max-width:960px){
  .hero-grid{grid-template-columns:1fr;gap:48px}
  .hero-visual{order:-1}
  .float-tag{display:none}
}

/* ═══════════════════════════════════════════════════════════════
   STAT CARDS
   ═══════════════════════════════════════════════════════════════ */
.stats-row{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-top:64px}
@media(max-width:768px){.stats-row{grid-template-columns:repeat(2,1fr)}}
@media(max-width:420px){.stats-row{grid-template-columns:1fr}}

.stat-card{
  background:var(--bg-card);
  border:1px solid var(--border);border-radius:var(--r-lg);
  padding:32px 28px;text-align:center;position:relative;overflow:hidden;
  transition:all .4s var(--ease);
}
.stat-card::before{content:'';position:absolute;top:0;left:0;right:0;height:3px;border-radius:3px 3px 0 0}
.stat-card:hover{transform:translateY(-6px);border-color:var(--border-hover);box-shadow:var(--shadow-lg)}

.stat-number{font-size:2.8rem;font-weight:700;letter-spacing:-.04em;line-height:1;margin-bottom:8px}
.stat-label{font-size:.72rem;color:var(--text-muted);font-weight:500;text-transform:uppercase;letter-spacing:.06em}

.sc-critical::before{background:var(--grad-critical)}
.sc-critical .stat-number{color:var(--critical)}
.sc-high::before{background:var(--grad-high)}
.sc-high .stat-number{color:var(--high)}
.sc-medium::before{background:var(--grad-medium)}
.sc-medium .stat-number{color:var(--medium)}
.sc-accent::before{background:var(--grad-hero)}
.sc-accent .stat-number{color:var(--accent)}

/* ═══════════════════════════════════════════════════════════════
   HEALTH SCORE
   ═══════════════════════════════════════════════════════════════ */
.health-section{padding:80px 0}
.health-grid{display:grid;grid-template-columns:280px 1fr;gap:56px;align-items:center}
@media(max-width:768px){.health-grid{grid-template-columns:1fr;justify-items:center;text-align:center}}

.score-ring{position:relative;width:260px;height:260px}
.score-ring svg{width:100%;height:100%;transform:rotate(-90deg)}
.score-ring-bg{fill:none;stroke:rgba(255,255,255,.03);stroke-width:10}
.score-ring-fill{
  fill:none;stroke-width:10;stroke-linecap:round;
  stroke-dasharray:0 754;
  animation:ring-draw 2.5s var(--ease) forwards;animation-delay:.8s;
}
@keyframes ring-draw{to{stroke-dasharray:var(--fill) 754}}
.score-center{
  position:absolute;inset:0;
  display:flex;flex-direction:column;align-items:center;justify-content:center;
}
.score-val{font-size:4.2rem;font-weight:700;letter-spacing:-.05em;line-height:1}
.score-of{font-size:1.4rem;font-weight:500;color:var(--text-muted)}
.score-lbl{font-size:.65rem;font-weight:600;text-transform:uppercase;letter-spacing:.14em;color:var(--text-muted);margin-top:4px}

.grade-badge{
  display:inline-flex;align-items:center;gap:8px;
  padding:8px 20px;border-radius:100px;
  font-size:.82rem;font-weight:500;margin-bottom:24px;
  background:var(--critical-bg);color:var(--critical);
  border:1px solid var(--critical-border);
  box-shadow:0 0 20px -6px rgba(248,113,113,.15);
}

.grades{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:20px}
@media(max-width:500px){.grades{grid-template-columns:1fr}}
.grade-row{
  display:flex;align-items:center;gap:12px;
  padding:12px 16px;background:var(--bg-card);
  border:1px solid var(--border);border-radius:var(--r-md);
  transition:all .3s var(--ease);
}
.grade-row:hover{background:var(--bg-card-hover);transform:translateX(4px);border-color:var(--border-hover)}
.grade-letter{
  width:34px;height:34px;border-radius:9px;
  display:flex;align-items:center;justify-content:center;
  font-weight:600;font-size:.78rem;flex-shrink:0;
}
.grade-name{font-size:.8rem;color:var(--text-secondary);font-weight:400}
.grade-score{font-size:.72rem;font-weight:600;color:var(--text-muted)}

/* ═══════════════════════════════════════════════════════════════
   EXECUTIVE SUMMARY
   ═══════════════════════════════════════════════════════════════ */
.exec-grid{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,360px),1fr));
  gap:16px;margin-top:40px;
}

.exec-card{
  background:var(--bg-card);
  border:1px solid var(--border);border-radius:var(--r-xl);
  padding:32px;position:relative;overflow:hidden;
  box-shadow:var(--shadow-sm);
  transition:all .4s var(--ease);
}
.exec-card:active,.opp-card:active,.stat-card:active{transform:translateY(-2px);transition-duration:.1s}
.exec-card::after{
  content:'';position:absolute;top:-40px;right:-40px;width:140px;height:140px;
  background:radial-gradient(circle,rgba(129,140,248,.04),transparent 70%);
  pointer-events:none;transition:opacity .4s ease;
}
.exec-card:hover{
  transform:translateY(-5px);border-color:var(--border-hover);
  box-shadow:0 20px 50px -14px rgba(0,0,0,.4);
}
.exec-card:hover::after{opacity:1.5}
.exec-icon{
  width:48px;height:48px;border-radius:14px;
  display:flex;align-items:center;justify-content:center;
  font-size:1.3rem;margin-bottom:20px;
}
.exec-card h3{margin-bottom:10px;font-size:1rem}
.exec-card p{color:var(--text-secondary);font-size:.86rem;line-height:1.75}

/* ═══════════════════════════════════════════════════════════════
   SEVERITY CHARTS
   ═══════════════════════════════════════════════════════════════ */
.chart-row{display:grid;grid-template-columns:1fr 1fr;gap:48px;margin-top:56px;align-items:center}
@media(max-width:768px){.chart-row{grid-template-columns:1fr}}

.bar-chart{display:flex;gap:24px;align-items:flex-end;height:260px}
.bar-group{flex:1;display:flex;flex-direction:column;align-items:center;gap:14px;height:100%;justify-content:flex-end}
.bar{
  width:100%;max-width:72px;border-radius:12px 12px 4px 4px;
  position:relative;transform:scaleY(0);transform-origin:bottom;
  animation:bar-grow 1.6s var(--ease) forwards;
}
@keyframes bar-grow{to{transform:scaleY(1)}}
.bar .bar-val{
  position:absolute;top:-36px;left:50%;transform:translateX(-50%);
  font-size:1.4rem;font-weight:600;letter-spacing:-.02em;
}
.bar-label{font-size:.68rem;font-weight:600;text-transform:uppercase;letter-spacing:.1em}
.bg-critical .bar{background:var(--grad-critical);animation-delay:.3s}
.bg-critical .bar-val,.bg-critical .bar-label{color:var(--critical)}
.bg-high .bar{background:var(--grad-high);animation-delay:.5s}
.bg-high .bar-val,.bg-high .bar-label{color:var(--high)}
.bg-medium .bar{background:var(--grad-medium);animation-delay:.7s}
.bg-medium .bar-val,.bg-medium .bar-label{color:var(--medium)}
.bg-low .bar{background:var(--grad-low);animation-delay:.9s}
.bg-low .bar-val,.bg-low .bar-label{color:var(--low)}

/* Donut */
.donut-wrap{display:flex;flex-direction:column;align-items:center;gap:28px}
.donut{position:relative;width:210px;height:210px}
.donut svg{width:100%;height:100%;transform:rotate(-90deg)}
.donut circle{fill:none;stroke-width:16;stroke-linecap:round}
.donut-track{stroke:rgba(255,255,255,.025)}
.donut-seg{stroke-dasharray:0 565;animation:dseg 2s var(--ease) forwards}
@keyframes dseg{to{stroke-dasharray:var(--seg) 565}}
.donut-center{
  position:absolute;inset:0;
  display:flex;flex-direction:column;align-items:center;justify-content:center;
}
.donut-center .big{font-size:2.6rem;font-weight:700;letter-spacing:-.03em}
.donut-center .small{font-size:.62rem;font-weight:500;text-transform:uppercase;letter-spacing:.12em;color:var(--text-muted)}
.donut-legend{display:flex;flex-direction:column;gap:10px}
.legend-row{display:flex;align-items:center;gap:10px;font-size:.82rem;font-weight:500}
.legend-dot{width:12px;height:12px;border-radius:4px;flex-shrink:0}

/* ═══════════════════════════════════════════════════════════════
   CATEGORY SCORE CARDS
   ═══════════════════════════════════════════════════════════════ */
.cat-scores-grid{
  display:grid;grid-template-columns:repeat(auto-fill,minmax(min(100%,240px),1fr));
  gap:14px;margin-top:40px;
}
.cat-score-card{
  background:var(--bg-card);
  border:1px solid var(--border);border-top:2px solid rgba(255,255,255,.04);border-radius:var(--r-lg);
  padding:24px;position:relative;overflow:hidden;
  transition:all .4s var(--ease);
}
.cat-score-card:hover{
  transform:translateY(-5px);border-color:var(--border-hover);
  box-shadow:var(--shadow-md);
}
.cat-score-top{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}
.cat-score-icon{
  width:40px;height:40px;border-radius:11px;
  display:flex;align-items:center;justify-content:center;font-size:1.15rem;
}
.cat-score-num{font-size:1.5rem;font-weight:700;letter-spacing:-.02em}
.cat-score-card h4{font-size:.86rem;font-weight:600;margin-bottom:10px}

/* Animated gauge */
.gauge{width:100%;height:4px;background:rgba(255,255,255,.03);border-radius:2px;overflow:hidden;margin-bottom:10px}
.gauge-fill{
  height:100%;border-radius:2px;
  transform:scaleX(0);transform-origin:left;
  transition:transform 1.4s var(--ease);
}
.gauge-visible .gauge-fill{transform:scaleX(1)!important}
.cat-score-meta{display:flex;justify-content:space-between;font-size:.68rem;color:var(--text-muted);font-weight:500}

/* ═══════════════════════════════════════════════════════════════
   SCREENSHOTS
   ═══════════════════════════════════════════════════════════════ */
.screenshot-grid{display:grid;grid-template-columns:1.4fr 1fr;gap:20px;margin-top:40px}
@media(max-width:768px){.screenshot-grid{grid-template-columns:1fr}}
.screenshot-card{
  border-radius:var(--r-xl);overflow:hidden;
  border:1px solid var(--border);background:var(--bg-card-solid);
  transition:all .4s var(--ease);position:relative;
}
.screenshot-card:hover{transform:translateY(-6px);box-shadow:var(--shadow-xl)}
.screenshot-card img{width:100%;display:block;transition:transform .5s var(--ease)}
.screenshot-card:hover img{transform:scale(1.03)}
.screenshot-cap{
  padding:16px 20px;display:flex;align-items:center;gap:10px;
  font-size:.78rem;font-weight:600;color:var(--text-muted);
}

/* ═══════════════════════════════════════════════════════════════
   PROGRAMS
   ═══════════════════════════════════════════════════════════════ */
.prog-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:40px}
@media(max-width:768px){.prog-grid{grid-template-columns:1fr}}
.prog-card{
  background:var(--bg-card);
  border:1px solid var(--border);border-radius:var(--r-lg);
  padding:28px;transition:all .4s var(--ease);
}
.prog-card:hover{transform:translateY(-4px);border-color:var(--border-hover)}
.prog-card h3{display:flex;align-items:center;gap:10px;margin-bottom:14px;font-size:1rem}
.prog-big{font-size:2.2rem;font-weight:700;line-height:1;margin-bottom:6px;letter-spacing:-.03em}
.tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:16px}
.tag{
  display:inline-block;padding:4px 10px;border-radius:6px;
  font-size:.68rem;font-weight:600;
  background:var(--accent-dim);border:1px solid rgba(129,140,248,.12);color:var(--accent);
}
.tag.closed{background:var(--critical-bg);border-color:var(--critical-border);color:var(--critical)}
.tag.minor{background:var(--low-bg);border-color:var(--low-border);color:var(--low)}
.tag.muted{background:rgba(255,255,255,.02);border-color:rgba(255,255,255,.05);color:var(--text-muted)}

/* ═══════════════════════════════════════════════════════════════
   OPPORTUNITIES
   ═══════════════════════════════════════════════════════════════ */
.opp-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr));gap:16px;margin-top:40px}

.opp-card{
  background:var(--bg-card);
  border:1px solid var(--border);border-radius:var(--r-xl);
  padding:32px;position:relative;overflow:hidden;
  box-shadow:var(--shadow-sm);
  transition:all .4s var(--ease);
}
.opp-card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px}
.opp-card:hover{transform:translateY(-5px);border-color:var(--border-hover);box-shadow:var(--shadow-md)}
.opp-impact{
  display:inline-block;padding:4px 12px;border-radius:100px;
  font-size:.64rem;font-weight:600;text-transform:uppercase;letter-spacing:.1em;margin-bottom:16px;
}
.opp-card h3{margin-bottom:10px;font-size:1.02rem}
.opp-card>p{color:var(--text-secondary);font-size:.86rem;line-height:1.7}
.opp-metrics{
  margin-top:20px;padding-top:20px;border-top:1px solid var(--border);
  display:grid;grid-template-columns:repeat(3,1fr);gap:12px;
}
@media(max-width:400px){.opp-metrics{grid-template-columns:1fr;gap:8px}}
.opp-metric{text-align:center}
.opp-metric-val{font-size:1.2rem;font-weight:600;line-height:1.2}
.opp-metric-lbl{font-size:.62rem;color:var(--text-muted);font-weight:500;text-transform:uppercase;letter-spacing:.06em}

/* ═══════════════════════════════════════════════════════════════
   CATEGORY DETAIL SECTIONS
   ═══════════════════════════════════════════════════════════════ */
.cat-section{padding:80px 0;border-top:1px solid var(--border)}
.cat-head{display:flex;align-items:center;gap:16px;margin-bottom:10px;flex-wrap:wrap}
@media(max-width:600px){
  .cat-right{margin-left:0;width:100%;margin-top:4px}
  .cat-icon{width:42px;height:42px}
}
.cat-icon{
  width:52px;height:52px;border-radius:14px;
  display:flex;align-items:center;justify-content:center;font-size:1.35rem;flex-shrink:0;
}
.cat-right{margin-left:auto;display:flex;align-items:center;gap:14px}
.cat-inline-score{font-size:1.4rem;font-weight:700;letter-spacing:-.02em}
.cat-count{
  padding:6px 14px;border-radius:100px;
  font-size:.68rem;font-weight:500;text-transform:uppercase;letter-spacing:.08em;
  border:1px solid var(--border);background:var(--bg-surface);color:var(--text-muted);
}

.issue-list{display:flex;flex-direction:column;gap:10px;margin-top:28px}
.issue-card{
  display:grid;grid-template-columns:auto 1fr;gap:16px;align-items:start;
  background:var(--bg-card);
  border:1px solid var(--border);border-radius:var(--r-md);
  padding:18px 22px;transition:all .25s ease;
}
.issue-card:hover{background:var(--bg-card-hover);border-color:var(--border-hover);transform:translateX(4px);box-shadow:var(--shadow-sm)}
.sev{
  padding:4px 10px;border-radius:6px;
  font-size:.62rem;font-weight:500;text-transform:uppercase;letter-spacing:.08em;
  white-space:nowrap;margin-top:2px;
}
.sev-c{background:var(--critical-bg);color:var(--critical);border:1px solid var(--critical-border)}
.sev-h{background:var(--high-bg);color:var(--high);border:1px solid var(--high-border)}
.sev-m{background:var(--medium-bg);color:var(--medium);border:1px solid var(--medium-border)}
.sev-l{background:var(--low-bg);color:var(--low);border:1px solid var(--low-border)}
.issue-title{font-weight:600;font-size:.9rem;margin-bottom:4px}
.issue-desc{color:var(--text-secondary);font-size:.82rem;line-height:1.7}

/* ═══════════════════════════════════════════════════════════════
   COMPETITIVE TABLE
   ═══════════════════════════════════════════════════════════════ */
.table-wrap{
  overflow-x:auto;margin-top:40px;
  border-radius:var(--r-lg);border:1px solid var(--border);
  background:var(--bg-card);
}
table{width:100%;border-collapse:collapse;font-size:.86rem}
thead{background:rgba(14,19,36,.95);backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);position:sticky;top:0;z-index:2}
th{
  padding:16px 22px;text-align:left;
  font-size:.68rem;font-weight:700;text-transform:uppercase;letter-spacing:.12em;
  color:var(--accent);border-bottom:1px solid var(--border);
}
td{padding:14px 22px;border-bottom:1px solid rgba(255,255,255,.03)}
tr:last-child td{border-bottom:none}
tbody tr{transition:all .15s ease}
tbody tr:hover{background:rgba(129,140,248,.05)}
td:nth-child(2),th:nth-child(2){background:rgba(248,113,113,.025)}
tbody tr:nth-child(even){background:rgba(255,255,255,.01)}
.ck{color:var(--low);font-weight:600;font-size:1rem;display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:var(--low-bg)}
.cx{color:var(--critical);font-weight:600;font-size:1rem;display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:var(--critical-bg)}

/* ═══════════════════════════════════════════════════════════════
   PRIORITIES
   ═══════════════════════════════════════════════════════════════ */
.priority-list{display:flex;flex-direction:column;gap:10px;margin-top:40px;position:relative}
@media(max-width:500px){
  .priority-item{grid-template-columns:40px 1fr;gap:12px;padding:12px 16px}
  .priority-item .sev{display:none}
  .priority-list::before{left:43px}
}
/* Connecting line */
.priority-list::before{
  content:'';position:absolute;left:51px;top:24px;bottom:24px;
  width:1px;background:linear-gradient(to bottom,var(--critical-border),var(--high-border),rgba(129,140,248,.1));
  z-index:0;
}
.priority-item{
  display:grid;grid-template-columns:52px 1fr auto;align-items:center;gap:16px;
  padding:14px 24px;background:var(--bg-card);
  border:1px solid var(--border);border-radius:var(--r-md);
  transition:all .3s var(--ease);position:relative;z-index:1;
}
.priority-item:hover{transform:translateX(6px);background:var(--bg-card-hover);border-color:var(--border-hover);box-shadow:var(--shadow-sm)}
.p-rank{
  width:36px;height:36px;border-radius:10px;
  display:flex;align-items:center;justify-content:center;
  font-size:.95rem;font-weight:600;font-variant-numeric:tabular-nums;
}
.priority-item:nth-child(-n+5) .p-rank{background:var(--critical-bg);color:var(--critical)}
.priority-item:nth-child(n+6):nth-child(-n+11) .p-rank{background:var(--high-bg);color:var(--high)}
.priority-item:nth-child(n+12) .p-rank{background:var(--accent-dim);color:var(--accent)}
.priority-item:nth-child(-n+5){border-left:3px solid rgba(248,113,113,.2)}
.p-name{font-weight:500;font-size:.88rem}

/* ═══════════════════════════════════════════════════════════════
   CALLOUT
   ═══════════════════════════════════════════════════════════════ */
.callout{
  background:linear-gradient(135deg,rgba(129,140,248,.05),rgba(192,132,252,.03));
  border:1px solid rgba(129,140,248,.12);
  border-radius:var(--r-lg);padding:32px;margin-top:32px;
  
}
.callout h3{color:var(--accent);margin-bottom:10px;font-size:1.05rem}
.callout p{color:var(--text-secondary);font-size:.88rem;line-height:1.7}
.callout.warn{
  background:linear-gradient(135deg,rgba(248,113,113,.04),rgba(251,191,36,.03));
  border-color:rgba(248,113,113,.12);
}
.callout.warn h3{color:var(--critical)}

/* ═══════════════════════════════════════════════════════════════
   STAMATS BRAND BAR
   ═══════════════════════════════════════════════════════════════ */
.brand-bar{
  position:fixed;top:0;left:0;right:0;z-index:1002;
  background:rgba(5,8,16,.95);
  border-bottom:1px solid var(--border);
  display:flex;align-items:center;justify-content:space-between;
  padding:10px 28px;height:44px;
  transition:opacity .4s ease,transform .4s ease;
}
.brand-bar.hide{opacity:0;transform:translateY(-100%);pointer-events:none}
.brand-bar-left{display:flex;align-items:center;gap:12px}
.brand-bar-logo{height:26px;width:26px;object-fit:contain;border-radius:6px}
.brand-bar-name{font-size:.78rem;font-weight:600;color:var(--text);letter-spacing:.02em}
@media(max-width:600px){
  .brand-bar-right{display:none}
  .brand-bar{padding:10px 16px}
}
.brand-bar-sep{width:1px;height:16px;background:var(--border)}
.brand-bar-tag{font-size:.68rem;font-weight:600;color:var(--text-muted)}
.brand-bar-right{font-size:.65rem;color:var(--text-muted);font-weight:600;letter-spacing:.04em}

/* Adjust sticky nav for brand bar */
.sticky-nav{top:44px}
.scroll-progress{top:44px}

/* Prepared by badge in hero */
.prepared-by{
  display:inline-flex;align-items:center;gap:10px;
  padding:8px 18px 8px 10px;
  background:rgba(255,255,255,.03);
  border:1px solid var(--border);border-radius:100px;
  margin-top:24px;
}
.prepared-by img{width:22px;height:22px;border-radius:5px}
.prepared-by span{font-size:.75rem;font-weight:600;color:var(--text-secondary)}
.prepared-by strong{color:var(--text);font-weight:700}

/* ═══════════════════════════════════════════════════════════════
   HERO CTA
   ═══════════════════════════════════════════════════════════════ */
.hero-ctas{margin-top:28px;display:flex;gap:12px;flex-wrap:wrap}
.hero-cta-primary{
  display:inline-flex;align-items:center;gap:8px;
  padding:12px 28px;border-radius:100px;
  background:var(--grad-hero);color:#fff;
  font-size:.86rem;font-weight:600;
  box-shadow:0 8px 32px -6px rgba(129,140,248,.35);
  transition:all .3s var(--ease);
}
.hero-cta-primary:hover{color:#fff;transform:translateY(-2px);box-shadow:0 12px 40px -6px rgba(129,140,248,.5)}
.hero-cta-secondary{
  display:inline-flex;align-items:center;
  padding:12px 28px;border-radius:100px;
  background:rgba(255,255,255,.04);border:1px solid var(--border);
  color:var(--text-secondary);font-size:.86rem;font-weight:500;
  transition:all .3s var(--ease);
}
.hero-cta-secondary:hover{background:rgba(255,255,255,.07);border-color:var(--border-hover);color:var(--text)}

/* ═══════════════════════════════════════════════════════════════
   FOOTER
   ═══════════════════════════════════════════════════════════════ */
.report-footer{text-align:center;padding:80px 28px;border-top:none;background-image:linear-gradient(90deg,transparent,rgba(129,140,248,.12),transparent);background-size:100% 1px;background-repeat:no-repeat;background-position:top}
.footer-logo{height:36px;width:36px;object-fit:contain;border-radius:8px;margin:0 auto 16px;display:block;opacity:.85;transition:opacity .3s ease}
.footer-logo:hover{opacity:1}
.report-footer .brand{
  font-weight:700;font-size:.95rem;margin-bottom:10px;
  background:var(--grad-hero);-webkit-background-clip:text;
  -webkit-text-fill-color:transparent;background-clip:text;
}
.report-footer p{color:var(--text-muted);font-size:.8rem}
.report-footer .prepared{margin-top:14px;font-size:.78rem;color:var(--text-secondary)}
.report-footer .prepared strong{color:var(--text);font-weight:700}
.report-footer .conf{margin-top:16px;color:rgba(255,255,255,.2);font-size:.68rem;text-transform:uppercase;letter-spacing:.14em}

/* ═══════════════════════════════════════════════════════════════
   DIVIDER
   ═══════════════════════════════════════════════════════════════ */
.section-divider{
  width:100%;height:1px;border:none;margin:0;
  background:linear-gradient(90deg,transparent,var(--border),transparent);
}

/* ═══════════════════════════════════════════════════════════════
   SCHEMA TABS
   ═══════════════════════════════════════════════════════════════ */
.schema-section{padding:80px 0;border-top:1px solid var(--border)}
.tab-bar{
  display:flex;gap:4px;margin-top:32px;margin-bottom:0;
  border-bottom:1px solid var(--border);overflow-x:auto;scrollbar-width:none;
}
.tab-bar::-webkit-scrollbar{display:none}
.tab-btn{
  padding:12px 20px;border:none;background:none;
  font-size:.82rem;font-weight:500;color:var(--text-muted);
  cursor:pointer;font-family:inherit;white-space:nowrap;
  border-bottom:2px solid transparent;
  transition:all .2s;position:relative;bottom:-1px;
}
.tab-btn:hover{color:var(--text-secondary)}
.tab-btn.active{color:var(--accent);border-bottom-color:var(--accent);border-bottom-width:3px}

.tab-panel{display:none;padding:28px 0}
.tab-panel.active{display:block}

.code-block{
  background:var(--bg-surface);border:1px solid var(--border);
  border-radius:var(--r-md);padding:24px;overflow-x:auto;
  font-family:'SF Mono',Consolas,'Liberation Mono',monospace;
  font-size:.82rem;line-height:1.8;color:var(--text-secondary);
  white-space:pre;tab-size:2;
}
.code-block .key{color:var(--accent)}
.code-block .str{color:var(--low)}
.code-block .cmt{color:var(--text-muted);font-style:italic}

.schema-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:20px}
@media(max-width:768px){.schema-grid{grid-template-columns:1fr}}

.schema-card{
  background:var(--bg-card);border:1px solid var(--border);
  border-radius:var(--r-md);padding:24px;
  transition:all .3s var(--ease);
}
.schema-card:hover{border-color:var(--border-hover);transform:translateY(-2px)}
.schema-card h4{font-size:.9rem;font-weight:600;margin-bottom:6px}
.schema-card p{font-size:.82rem;color:var(--text-secondary);line-height:1.65}
.schema-card .schema-type{
  display:inline-block;padding:3px 10px;border-radius:4px;
  font-size:.68rem;font-weight:500;margin-bottom:12px;
  background:var(--accent-dim);color:var(--accent);
}
.schema-status{
  display:inline-flex;align-items:center;gap:6px;
  margin-top:12px;font-size:.72rem;font-weight:500;
}
.schema-status.missing{color:var(--critical)}
.schema-status.present{color:var(--low)}
.status-dot{width:6px;height:6px;border-radius:50%}
.status-dot.red{background:var(--critical)}
.status-dot.green{background:var(--low)}

.impact-bar{
  display:flex;align-items:center;gap:16px;
  margin-top:24px;padding:20px 24px;
  background:var(--bg-card);border:1px solid var(--border);
  border-radius:var(--r-md);
}
.impact-bar .impact-icon{
  width:44px;height:44px;border-radius:12px;
  display:flex;align-items:center;justify-content:center;
  font-size:1.2rem;flex-shrink:0;
}
.impact-bar p{font-size:.84rem;color:var(--text-secondary);line-height:1.6}
.impact-bar strong{color:var(--text);font-weight:600}

/* ═══════════════════════════════════════════════════════════════
   PRINT
   ═══════════════════════════════════════════════════════════════ */
@media print{
  @page{margin:1.5cm 2cm}
  body{background:#fff;color:#111}
  body.nav-open{margin-left:0}
  .ambient,.scroll-progress,.sticky-nav,body::after,.hero-mesh,.deco-ring,.float-tag,
  .chat-fab,.chat-panel,.ai-intro-overlay,.brand-bar{display:none!important}
  .gradient-text{-webkit-text-fill-color:initial!important;background:none!important;color:#111!important}
  .glass,.stat-card,.exec-card,.issue-card,.opp-card,.cat-score-card,.prog-card,.priority-item,.screenshot-card{
    break-inside:avoid;border-color:#e2e8f0;background:#fff;backdrop-filter:none;
  }
  .bar{transform:scaleY(1)!important}
  .donut-seg{stroke-dasharray:var(--seg) 565!important}
  .score-ring-fill{stroke-dasharray:var(--fill) 754!important}
  .gauge-fill{transform:scaleX(1)!important}
  .sev-c{color:#dc2626!important;border-color:#dc2626!important}
  .sev-h{color:#d97706!important;border-color:#d97706!important}
  .sev-m{color:#2563eb!important;border-color:#2563eb!important}
  .sev-l{color:#059669!important;border-color:#059669!important}
  section{padding:40px 0;page-break-inside:avoid}
  .issue-card{page-break-inside:avoid}
  .hero{min-height:auto}
  img{max-width:100%;height:auto}
  svg{print-color-adjust:exact;-webkit-print-color-adjust:exact}
}
`
