// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.
// Re-run `node packages/server/src/reports/extractor.mjs` after editing coe-gap-analysis-report.html.
export const CHAT_STYLES = `
.chat-fab{
  position:fixed;bottom:28px;right:28px;z-index:999;
  width:56px;height:56px;border-radius:50%;
  background:var(--grad-hero);border:none;cursor:pointer;
  display:flex;align-items:center;justify-content:center;
  box-shadow:0 8px 32px rgba(129,140,248,.3);
  transition:transform .3s var(--ease),box-shadow .3s ease;
}
.chat-fab:hover{transform:scale(1.08);box-shadow:0 12px 40px rgba(129,140,248,.4)}
.chat-fab:not(.hidden){animation:fab-breathe 3s ease-in-out infinite}
.chat-fab:hover{animation:none}
@keyframes fab-breathe{0%,100%{box-shadow:0 8px 32px rgba(129,140,248,.3)}50%{box-shadow:0 8px 40px rgba(129,140,248,.5)}}
.chat-fab.hidden{transform:scale(0);pointer-events:none}

.chat-panel{
  position:fixed;bottom:96px;right:28px;z-index:999;
  width:380px;max-height:520px;
  background:var(--bg-surface);border:1px solid var(--border);
  border-radius:var(--r-xl);overflow:hidden;
  display:flex;flex-direction:column;
  box-shadow:var(--shadow-xl);
  transform:scale(.9) translateY(20px);opacity:0;pointer-events:none;
  transition:all .35s var(--ease);
}
.chat-panel.open{transform:scale(1) translateY(0);opacity:1;pointer-events:all}
@media(max-width:500px){
  .chat-panel{right:8px;left:8px;width:auto;bottom:80px;max-height:70vh}
  .chat-fab{bottom:16px;right:16px;width:48px;height:48px}
}

.chat-header{
  display:flex;align-items:center;justify-content:space-between;
  padding:14px 18px;border-bottom:1px solid var(--border);
  background:rgba(14,19,36,.8);
}
.chat-header-left{display:flex;align-items:center;gap:10px;font-size:.82rem;font-weight:600;color:var(--text)}
.chat-close{
  background:none;border:none;color:var(--text-muted);font-size:1.3rem;
  cursor:pointer;width:28px;height:28px;border-radius:6px;
  display:flex;align-items:center;justify-content:center;
  transition:all .2s;
}
.chat-close:hover{background:rgba(255,255,255,.06);color:var(--text)}

.chat-messages{
  flex:1;overflow-y:auto;padding:16px;
  display:flex;flex-direction:column;gap:12px;
  min-height:200px;max-height:360px;
}
.chat-msg{
  padding:12px 16px;border-radius:var(--r-md);
  font-size:.84rem;line-height:1.65;max-width:90%;
}
.chat-msg.bot{
  background:var(--bg-card);border:1px solid var(--border);
  color:var(--text-secondary);align-self:flex-start;
}
.chat-msg.user{
  background:rgba(129,140,248,.12);border:1px solid rgba(129,140,248,.15);
  color:var(--text);align-self:flex-end;
}
.chat-msg.typing{color:var(--text-muted);font-style:italic}

.chat-input-row{
  display:flex;gap:8px;padding:12px 14px;
  border-top:1px solid var(--border);background:rgba(14,19,36,.6);
}
.chat-input{
  flex:1;background:var(--bg-card);border:1px solid var(--border);
  border-radius:var(--r-sm);padding:10px 14px;
  color:var(--text);font-size:.84rem;font-family:inherit;
  outline:none;transition:border-color .2s;
}
.chat-input:focus{border-color:rgba(129,140,248,.3)}
.chat-input::placeholder{color:var(--text-muted)}
.chat-send{
  background:var(--grad-hero);border:none;border-radius:var(--r-sm);
  width:38px;height:38px;display:flex;align-items:center;justify-content:center;
  cursor:pointer;color:#fff;flex-shrink:0;transition:transform .2s;
}
.chat-send:hover{transform:scale(1.06)}
`
