// AUTO-GENERATED by reports/extractor.mjs — DO NOT EDIT BY HAND.
// Re-run `node packages/server/src/reports/extractor.mjs` after editing coe-gap-analysis-report.html.
export const INTRO_STYLES = `
.ai-intro-overlay{
  position:fixed;bottom:96px;right:28px;z-index:10000;
  opacity:0;pointer-events:none;
  transition:opacity .4s ease,transform .5s cubic-bezier(.16,1,.3,1);
  transform:scale(.9) translateY(16px);
}
.ai-intro-overlay.show{opacity:1;pointer-events:all;transform:scale(1) translateY(0)}

.ai-intro-card{
  position:relative;
  width:380px;
  background:linear-gradient(165deg,rgba(17,22,40,.97),rgba(10,14,26,.99));
  border:1px solid rgba(129,140,248,.15);
  border-radius:24px;padding:40px 32px 32px;
  text-align:center;
  box-shadow:0 32px 80px -16px rgba(0,0,0,.6),0 0 60px -16px rgba(129,140,248,.1);
  overflow:hidden;
}

.ai-intro-glow{
  position:absolute;top:-60px;left:50%;transform:translateX(-50%);
  width:300px;height:200px;
  background:radial-gradient(ellipse,rgba(129,140,248,.12),transparent 70%);
  pointer-events:none;
}

.ai-intro-sparkle{
  position:absolute;width:4px;height:4px;border-radius:50%;
  background:#818cf8;
  animation:sparkle 2.5s ease-in-out infinite;
}
.s1{top:18%;left:15%;animation-delay:0s}
.s2{top:12%;right:20%;animation-delay:.8s}
.s3{bottom:25%;right:12%;animation-delay:1.6s}
@keyframes sparkle{
  0%,100%{opacity:0;transform:scale(0)}
  50%{opacity:.7;transform:scale(1)}
}

.ai-intro-icon-wrap{
  position:relative;width:72px;height:72px;
  margin:0 auto 24px;
}
.ai-intro-icon{
  width:72px;height:72px;border-radius:22px;
  background:var(--grad-hero);
  display:flex;align-items:center;justify-content:center;
  position:relative;z-index:1;
  box-shadow:0 12px 40px -8px rgba(129,140,248,.35);
}
.ai-intro-pulse-ring{
  position:absolute;inset:-8px;border-radius:28px;
  border:2px solid rgba(129,140,248,.2);
  animation:intro-pulse 2.5s ease-in-out infinite;
}
.ai-intro-pulse-ring.r2{inset:-18px;border-radius:34px;animation-delay:.5s;border-color:rgba(129,140,248,.1)}
@keyframes intro-pulse{
  0%,100%{transform:scale(1);opacity:.5}
  50%{transform:scale(1.08);opacity:.15}
}

.ai-intro-badge{
  display:inline-block;
  padding:4px 14px;border-radius:100px;
  font-size:.65rem;font-weight:600;text-transform:uppercase;letter-spacing:.12em;
  background:rgba(129,140,248,.1);border:1px solid rgba(129,140,248,.2);
  color:var(--accent);margin-bottom:16px;
}

.ai-intro-title{
  font-size:1.5rem;font-weight:600;letter-spacing:-.02em;
  margin-bottom:12px;color:var(--text);line-height:1.2;
}

.ai-intro-desc{
  font-size:.88rem;color:var(--text-secondary);line-height:1.7;
  margin-bottom:24px;
}
.ai-intro-desc strong{color:var(--accent-bright);font-weight:600}

.ai-intro-examples{
  display:flex;flex-wrap:wrap;justify-content:center;gap:8px;
  margin-bottom:28px;
}
.ai-intro-chip{
  padding:7px 16px;border-radius:100px;
  background:rgba(255,255,255,.04);border:1px solid var(--border);
  color:var(--text-secondary);font-size:.78rem;font-weight:500;
  cursor:pointer;transition:all .2s;font-family:inherit;
}
.ai-intro-chip:hover{background:rgba(129,140,248,.08);border-color:rgba(129,140,248,.2);color:var(--text)}

.ai-intro-cta{
  display:inline-flex;align-items:center;gap:8px;
  padding:12px 32px;border-radius:14px;
  background:var(--grad-hero);border:none;
  color:#fff;font-size:.88rem;font-weight:600;
  cursor:pointer;font-family:inherit;
  box-shadow:0 8px 32px -6px rgba(129,140,248,.35);
  transition:all .3s var(--ease);
}
.ai-intro-cta:hover{transform:translateY(-2px);box-shadow:0 12px 40px -6px rgba(129,140,248,.45)}

.ai-intro-dismiss{
  display:block;width:100%;margin-top:14px;
  background:none;border:none;
  color:var(--text-muted);font-size:.78rem;font-weight:500;
  cursor:pointer;font-family:inherit;
  transition:color .2s;padding:8px;
}
.ai-intro-dismiss:hover{color:var(--text-secondary)}

@media(max-width:500px){
  .ai-intro-overlay{right:8px;left:8px;bottom:80px}
  .ai-intro-card{width:auto;padding:32px 24px 28px;border-radius:20px}
  .ai-intro-title{font-size:1.2rem}
}
`
