export { ClientAIChat } from "./ClientAIChat"
export { SectionHeader } from "./SectionHeader"
export { MetricCard } from "./MetricCard"
export { LinkAnswerModal } from "./LinkAnswerModal"
export { AddClientModal } from "./AddClientModal"
export { ChatMarkdown } from "./ChatMarkdown"
export { ClientRoster } from "./ClientRoster"
export { ClientDetailHeader } from "./ClientDetailHeader"
export { ClientOverviewTab } from "./ClientOverviewTab"
export { ClientAssetsTab } from "./ClientAssetsTab"
export { ClientDocumentsTab } from "./ClientDocumentsTab"
export { ClientBrandKitTab } from "./ClientBrandKitTab"
export { ClientPortfolioProvider, useClientData, useClientSelection } from "./ClientPortfolioContext"
export type { ClientChatContext } from "./types"
export type { DetailTab, ClientWithCounts, SectorFilter } from "./ClientPortfolioContext"
